### ISSUE TITLE
is possible to load tf model from memory buffer

### ISSUE THREAD

**Issue by zjd1988** [ika-rwth-aachen/tensorflow_cpp#10]
wonderful job, but i also want to load model form memory, I google that, but can not find any useful info. Do you have any solution

**Comment by lreiher** [comment]
I guess you need to provide a little more info on what exactly you intend to do. In what form do you have your model in memory?

**Comment by zjd1988** [comment]
hi @lreiher ,thank for your reply, here is a c++ demo code
```
int test_file_size(std::string file_name)
{
	std::ifstream in(file_name.c_str(), std::ios::binary);
	if (!in.is_open()) {
		std::cout << "fail to open file\n";
		return -1;
	}
 
	std::streampos begin, end;
	begin = in.tellg();
	in.seekg(0, std::ios::end);
	end = in.tellg();
 
	in.close();
 
	std::cout << "this file's size is: " << (end - begin) << " bytes.\n";
 
	return 0;
}

int main()
{
	std::string  model_file = "savedmodel.pb"
	int file_size = test_file_size(model_file);
	std::vector<uin8_t>  model_data(file_size);
	std::ifstream fin(filename.c_str(), std::ios::binary | std::ios::in);
	if (!fin) {
		std::cerr << "error: open file for input failed!" << std::endl;
		return -1;
	}
	fin.read(model_data.data(), file_size);
        fin.close();
       tensorflow_cpp::Model model;
       model.loadModelFromData(model_data.data(), file_size);
       return 0;
}
  
```
is possible implement a function like loadModelFromData to load model?

**Comment by lreiher** [comment]
Kind of depends on the C++ APIs available by TensorFlow. For example, the actual TensorFlow API call for loading a saved model is called [here](https://github.com/ika-rwth-aachen/tensorflow_cpp/blob/main/include/tensorflow_cpp/saved_model_utils.h#L66).

If you find a suitable API for the desired behavior, I would also be happy to look over a PR that is exposing this API in this `tensorflow_cpp` wrapper convenience library.

Alternatively, I guess you could first write the datastream to a file and then load from there?

**Comment by zjd1988** [comment]
Hi @lreiher I google that, not found a suitable solution.
